[[sessions]]
date = "2026-04-06"
time_seconds = 300
correct = 5
total = 5
problem_types = [
    "division",
    "multiplication",
    "subtraction",
    "multiplication",
    "addition",
]

[[sessions]]
date = "2026-04-07"
time_seconds = 300
correct = 4
total = 5
problem_types = [
    "division",
]

[[sessions]]
date = "2026-04-08"
time_seconds = 180
correct = 5
total = 5
problem_types = []

[[sessions]]
date = "2026-04-10"
time_seconds = 300
correct = 4
total = 5
problem_types = [
    "division",
]

[[sessions]]
date = "2026-04-13"
time_seconds = 180
correct = 5
total = 5
problem_types = [
    "multiplication",
    "subtraction",
    "subtraction",
    "multiplication",
    "addition",
]
