slug = "cv"
title = "CV"
summary = "Computer vision."
parent = "ml"
related = []
created = "2026-04-29"
updated = "2026-04-29"
last_maintained = "2026-04-29"
docs = [
    { slug = "vit", hook = "" },
]
