slug = "foundational-papers"
title = "Foundational Papers"
summary = "Seminal papers in ML."
related = []
created = "2026-04-29"
updated = "2026-04-29"
last_maintained = "2026-04-29"
docs = [
    { slug = "attention-is-all-you-need", hook = "" },
]
