slug = "nlp"
title = "NLP"
summary = "Natural language processing."
parent = "ml"
related = []
created = "2026-04-29"
updated = "2026-04-29"
last_maintained = "2026-04-29"
docs = [
    { slug = "transformer", hook = "" },
    { slug = "bert", hook = "" },
    { slug = "vit", hook = "" },
]
