[[tasks]]
slug = "lunch_mike"
name = "Lunch Mike"
path = "./management/tasks/lunch_mike.toml"
due = "2026-03-18T13:00:00+02:00"
parent = ""

[[tasks]]
slug = "hep_studii"
name = "HEP // Studii"
path = "./management/tasks/hep_studii.toml"
due = "2026-03-20T11:00:00+02:00"
parent = ""

[[tasks]]
slug = "charge_yhat_vouchers_project"
name = "CHARGE | Yhat - Vouchers project"
path = "./management/tasks/charge_yhat_vouchers_project.toml"
due = "2026-03-20T13:00:00+02:00"
parent = ""

[[tasks]]
slug = "migrate_to_safari"
name = "Migrate to Safari"
path = "./management/tasks/migrate_to_safari.toml"
due = "2026-03-21T00:00:00"
parent = ""

[[tasks]]
slug = "move_yhat_to_de_havilland"
name = "Move Yhat to De Havilland"
path = "./management/tasks/move_yhat_to_de_havilland.toml"
due = "2026-03-22T00:00:00"
parent = ""

[[tasks]]
slug = "fw_philip_tendani_catchup"
name = "FW: Philip Tendani catchup"
path = "./management/tasks/fw_philip_tendani_catchup.toml"
due = "2026-03-23T13:30:00+02:00"
parent = ""

[[tasks]]
slug = "charge_yhat_check_in"
name = "CHARGE Yhat Check-In"
path = "./management/tasks/charge_yhat_check_in.toml"
due = "2026-03-24T09:00:00+02:00"
parent = ""

[[tasks]]
slug = "test_gcal_sync"
name = "Test gcal sync"
path = "./management/tasks/test_gcal_sync.toml"
due = "2026-04-05T16:00:00+02:00"
parent = ""
