[[tasks]]
slug = "weekly_standup"
name = "Weekly standup"
path = "./management/tasks/weekly_standup.toml"
due = "2026-03-31T00:00:00"
parent = ""

[[tasks]]
slug = "look_into_new_laptop"
name = "Look into new laptop"
path = "./management/tasks/look_into_new_laptop.toml"
parent = ""

[[tasks]]
slug = "submit_tax_return"
name = "Submit tax return"
path = "./management/tasks/submit_tax_return.toml"
due = "2026-04-05"
parent = ""
