name = "Add Typst soft type system to Praxis"
slug = "add_typst_soft_type_system_to_praxis"
description = ""
status = "todo"
created = "2026-05-05"
tags = []
recurrence = ""
gcal_event_id = ""
last_modified = "2026-05-05T17:23:27.050026"
has_subtasks = false
parent = ""
