name = "Add immediate charging stop when preauth increment loop reaches max retries on ev-ledger"
slug = "add_immediate_charging_stop_when_preauth_increment_loop_reaches_max_retries_on_ev_ledger"
description = ""
status = "todo"
created = "2026-04-20"
due = "2026-04-21"
tags = []
recurrence = ""
gcal_event_id = ""
last_modified = "2026-04-20T17:51:19.550108"
has_subtasks = false
parent = ""
