name = "Lunch with Mike"
slug = "lunch_with_mike"
description = ""
status = "todo"
created = "2026-04-23"
due = "2026-05-04T12:00:00"
tags = []
recurrence = ""
gcal_event_id = ""
last_modified = "2026-04-30T13:16:20.566664"
has_subtasks = false
parent = ""
