name = "Lunch with Mike"
slug = "lunch_with_mike"
description = ""
status = "todo"
created = "2026-04-23"
due = "2026-05-06T13:00:00"
tags = []
recurrence = ""
gcal_event_id = ""
last_modified = "2026-05-04T14:17:12.032247"
has_subtasks = false
parent = ""
