name = "Refill water"
slug = "refill_water"
description = ""
status = "todo"
created = "2026-04-01"
due = "2026-04-07T13:00:00"
tags = []
recurrence = ""
gcal_event_id = ""
last_modified = "2026-04-06T13:22:19.493450"
has_subtasks = false
parent = ""
