name = "Refill water"
slug = "refill_water"
description = ""
status = "todo"
created = "2026-04-01"
due = "2026-04-06"
tags = []
recurrence = ""
gcal_event_id = ""
last_modified = "2026-04-02T21:28:04.347217"
has_subtasks = false
parent = ""
