name = "Research Cargo monorepo handling for Rust track"
slug = "research_cargo_monorepo_handling_for_rust_track"
description = ""
status = "todo"
created = "2026-04-06"
tags = [
    "nexus-learn",
]
recurrence = ""
gcal_event_id = ""
last_modified = "2026-04-06T19:09:37.674229"
has_subtasks = false
parent = ""
