name = "Scaffold Nexus Learn C course"
slug = "scaffold_nexus_learn_c_course"
description = ""
status = "todo"
created = "2026-04-06"
tags = [
    "priority-low",
    "nexus-learn",
]
recurrence = ""
gcal_event_id = ""
last_modified = "2026-04-15T12:48:33.491867"
has_subtasks = false
parent = ""
