name = "Anro van Tonder's birthday"
slug = "anro_van_tonder_s_birthday_gcal"
description = ""
status = "todo"
created = "2026-03-31"
due = "2055-05-13"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "j5ti2hldnse4n02bk3o8m9gaic_20550513"
last_modified = "2026-03-31T12:49:44.066751"
has_subtasks = false
parent = ""
