name = "Benjamin Van heerden's birthday"
slug = "benjamin_van_heerden_s_birthday_gcal"
description = ""
status = "todo"
created = "2026-03-31"
due = "2032-07-30"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "1h2iemcphi3k9im3ftttr7b2k4_20320730"
last_modified = "2026-03-31T12:47:20.654634"
has_subtasks = false
parent = ""
