name = "Bunk: Spring Loader Double Sun Album Launch - Railways Cafe"
slug = "bunk_spring_loader_double_sun_album_launch_railways_cafe"
description = ""
status = "todo"
created = "2026-03-31"
due = "2024-02-02T18:00:00+02:00"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "_6tlnaqrle5p6cpb4dhmj4phpehqjcpj6e5p74q9he5qmqt9g6dnncrrh6pqmed1pcsqm4r3kc8q68prddpqn2oj8d5p70rr1c9nmgqhpdto30"
last_modified = "2026-03-31T12:47:19.908625"
has_subtasks = false
parent = ""
