name = "Buy groceries"
slug = "buy_groceries"
description = ""
status = "todo"
created = "2026-03-31"
tags = [
    "personal",
]
recurrence = ""
gcal_event_id = ""
last_modified = "2026-03-31T15:21:46.743053"
has_subtasks = false
parent = ""
