name = "ChargePulse Software MVP"
slug = "chargepulse_software_mvp"
description = ""
status = "todo"
created = "2026-03-31"
due = "2025-07-02T16:00:00+02:00"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "58vd7kv68lal6tkufn6ofufq5n"
last_modified = "2026-03-31T12:47:20.025460"
has_subtasks = false
parent = ""
