name = "Ferdi Tutoring"
slug = "ferdi_tutoring"
description = ""
status = "todo"
created = "2026-03-31"
due = "2019-03-03T10:00:00+02:00"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "c8s3cphn6kq30bb4coq64b9kc5hj2b9o6os32b9gcdh38c9l60o38dpock"
last_modified = "2026-03-31T12:47:19.429125"
has_subtasks = false
parent = ""
