name = "Flight to Cape Town (FA 206)"
slug = "flight_to_cape_town_fa_206"
description = ""
status = "todo"
created = "2026-03-31"
due = "2024-04-10T12:15:00+02:00"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "_6tlnaqrle5p6cpb4dhmj4phpehq6se9n6dn6oebgdtk6id3edks6grjcdppn8q9nephn2cjee9lncqr1c4q70cbm6lo38cb36lj6gq1lehi6e"
last_modified = "2026-03-31T12:47:19.915528"
has_subtasks = false
parent = ""
