name = "FW: 1457 Full Stack Java Developer (Spotlight)- Benjamin van Heerden (Direct Referral) - Confirmed"
slug = "fw_1457_full_stack_java_developer_spotlight_benjamin_van_heerden_direct_referral_confirmed"
description = ""
status = "todo"
created = "2026-03-31"
due = "2021-06-23T11:00:00+02:00"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "_60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g84o3ighn891k4c9n6oq48dpg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g8l1k6ci58gs36c1j6h0k6e1k850kah9h70rjacpi750jeha38h1g"
last_modified = "2026-03-31T12:47:19.500245"
has_subtasks = false
parent = ""
