name = "Gideon Oosthuizen Beleggingsgesprek"
slug = "gideon_oosthuizen_beleggingsgesprek"
description = ""
status = "todo"
created = "2026-03-31"
due = "2020-04-23T10:00:00+02:00"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "_6h344ga58h2jab9k8h33cb9k8gsk6b9o6os3ib9i68sk8dpm8or34cpn8kllkjqf9l6kahak9574ejil9l14akhq74p3ecpm64oj6dpk68"
last_modified = "2026-03-31T12:47:19.477693"
has_subtasks = false
parent = ""
