name = "Go to dentist"
slug = "go_to_dentist"
description = "Annual checkup. Dr. Smith's office on Main St."
status = "todo"
created = "2026-03-31"
due = "2026-04-15T10:00:00"
tags = [
    "health",
    "personal",
]
recurrence = ""
gcal_event_id = ""
last_modified = "2026-03-31T12:33:38.788456"
has_subtasks = false
parent = ""
