name = "Happy birthday!"
slug = "happy_birthday"
description = ""
status = "todo"
created = "2026-03-31"
due = "2026-07-30"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "u4rkjtlb4klepjlvklpufmu71k_20260730"
last_modified = "2026-03-31T12:49:43.382413"
has_subtasks = false
parent = ""
