name = "HEP // Studii"
slug = "hep_studii"
description = ""
status = "todo"
created = "2026-03-31"
due = "2026-03-20T11:00:00+02:00"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "_68o34dhg6cojcl1h68p34chkb8mjgcpp6gs36cpg6os36g3nclh2qs3idti2qtbj60r2qtj164mnepb2dtliqdpmcos3gdpn74q68bbid8qm6s0"
last_modified = "2026-03-31T12:49:43.373158"
has_subtasks = false
parent = ""
