name = "Learning - SQL Fundamentals DataCamp"
slug = "learning_sql_fundamentals_datacamp"
description = ""
status = "todo"
created = "2026-03-31"
due = "2022-03-14T20:00:00+02:00"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "29pvcavdl6gmm1ff6rs10jheej_20220314T180000Z"
last_modified = "2026-03-31T12:47:19.524308"
has_subtasks = false
parent = ""
