name = "Learning time - Building Deep Learning Models with TensorFlow"
slug = "learning_time_building_deep_learning_models_with_tensorflow"
description = ""
status = "todo"
created = "2026-03-31"
due = "2022-03-14T08:00:00+02:00"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "52lfbhe8rusbfck0scseumclsj_20220314T060000Z"
last_modified = "2026-03-31T12:47:19.520814"
has_subtasks = false
parent = ""
