name = "Learning - SQL Fundamentals DataCamp"
slug = "learning_sql_fundamentals_datacamp_gcal"
description = ""
status = "todo"
created = "2026-03-31"
due = "2022-03-16T20:00:00+02:00"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "29pvcavdl6gmm1ff6rs10jheej_20220316T180000Z"
last_modified = "2026-03-31T12:47:19.546664"
has_subtasks = false
parent = ""
