name = "Marike Weys's birthday"
slug = "marike_weys_s_birthday"
description = ""
status = "todo"
created = "2026-03-31"
due = "1997-04-19"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "p12o9fnp8ngdhl5ii8pjh4eiac_19970419"
last_modified = "2026-03-31T12:47:19.341938"
has_subtasks = false
parent = ""
