name = "Marike Weys's birthday"
slug = "marike_weys_s_birthday"
description = ""
status = "todo"
created = "2026-03-31"
due = "2026-04-19"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "p12o9fnp8ngdhl5ii8pjh4eiac_20260419"
last_modified = "2026-03-31T12:49:43.378802"
has_subtasks = false
parent = ""
