name = "Maths/Logic Assessment - Benjamin van Heerden"
slug = "maths_logic_assessment_benjamin_van_heerden"
description = ""
status = "todo"
created = "2026-03-31"
due = "2022-04-28T11:00:00+02:00"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "_fcs48h1j8gsj4c9d84p3gh1d6gp4ae1d752j6dpd8l1k8ca46l148c1l8d0nq"
last_modified = "2026-03-31T12:47:19.815346"
has_subtasks = false
parent = ""
