name = "Migrate to Safari"
slug = "migrate_to_safari"
description = ""
status = "todo"
created = "2026-03-31"
due = "2026-03-21"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "_8op3adho8go44b9o70rj2b9k752k4ba265338ba26sp32h1o75242dq38k"
last_modified = "2026-03-31T12:49:43.374817"
has_subtasks = false
parent = ""
