name = "Move Yhat to De Havilland"
slug = "move_yhat_to_de_havilland"
description = ""
status = "todo"
created = "2026-03-31"
due = "2026-03-22"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "_70p3ec268kq38ba164qj6b9k68r42ba16cq38b9i88qjge1h88r36dq46g"
last_modified = "2026-03-31T12:49:43.375596"
has_subtasks = false
parent = ""
