name = "Newbie Walkthrough Africa: Learn how to use Binance"
slug = "newbie_walkthrough_africa_learn_how_to_use_binance_gcal"
description = ""
status = "todo"
created = "2026-03-31"
due = "2021-05-21T18:00:00+02:00"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "sjqbmr0sf86ritabh87c4r4f4k_20210521T160000Z"
last_modified = "2026-03-31T12:47:19.496910"
has_subtasks = false
parent = ""
