name = "Newbie Walkthrough Africa: Learn how to use Binance"
slug = "newbie_walkthrough_africa_learn_how_to_use_binance"
description = ""
status = "todo"
created = "2026-03-31"
due = "2021-05-19T18:00:00+02:00"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "sjqbmr0sf86ritabh87c4r4f4k_20210519T160000Z"
last_modified = "2026-03-31T12:47:19.493471"
has_subtasks = false
parent = ""
