name = "Remind me to do something"
slug = "remind_me_to_do_something"
description = ""
status = "todo"
created = "2026-03-31"
due = "2018-10-22T22:00:00+02:00"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "cdim8cpnc4qm4b9n6crjab9k6op34bb16ti36b9m64q6cohp6phjce1mcc"
last_modified = "2026-03-31T12:47:19.404995"
has_subtasks = false
parent = ""
