name = "St 2 phy 356"
slug = "st_2_phy_356"
description = ""
status = "todo"
created = "2026-03-31"
due = "2019-03-20T08:00:00+02:00"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "chi3gchj74p36bb268p3eb9k6cq3ib9p6hgj8b9i74q3gd9l6pgjcopnck"
last_modified = "2026-03-31T12:47:19.444225"
has_subtasks = false
parent = ""
