name = "The Big Pitch 2025 - Qualifier One."
slug = "the_big_pitch_2025_qualifier_one"
description = ""
status = "todo"
created = "2026-03-31"
due = "2025-04-23T18:00:00+02:00"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "deis5r87kvqnhk39p6u810q5v4"
last_modified = "2026-03-31T12:47:19.972552"
has_subtasks = false
parent = ""
