name = "Tutoring (Shawnri + Juanice Gr. 12)"
slug = "tutoring_shawnri_juanice_gr_12_gcal"
description = ""
status = "todo"
created = "2026-03-31"
due = "2019-02-21T17:00:00+02:00"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "6oqjic1pcpgj8b9m60r6ab9k74smcbb26csjib9p70p6cpj464q36e1g6c_20190221T150000Z"
last_modified = "2026-03-31T12:47:19.422195"
has_subtasks = false
parent = ""
