name = "Get dentist number"
slug = "get_dentist_number"
description = ""
status = "todo"
created = "2026-03-31"
tags = []
recurrence = ""
gcal_event_id = ""
last_modified = "2026-03-31T12:37:57.748434"
has_subtasks = false
parent = "make_appointment"
