name = "Foundations"
current_goal = "Introduction and Motivation"

[[goals]]
name = "Introduction and Motivation"
status = "todo"
reference = "./learn/rust/reference/python-book/ch01-introduction-and-motivation.md"

[[goals]]
name = "Getting Started"
status = "todo"
reference = "./learn/rust/reference/python-book/ch02-getting-started.md"

[[goals]]
name = "Built-in Types and Variables"
status = "todo"
reference = "./learn/rust/reference/python-book/ch03-built-in-types-and-variables.md"

[[goals]]
name = "Control Flow"
status = "todo"
reference = "./learn/rust/reference/python-book/ch04-control-flow.md"

[[goals]]
name = "Data Structures and Collections"
status = "todo"
reference = "./learn/rust/reference/python-book/ch05-data-structures-and-collections.md"

[[goals]]
name = "Enums and Pattern Matching"
status = "todo"
reference = "./learn/rust/reference/python-book/ch06-enums-and-pattern-matching.md"
