name = "calculus"
current_goal = "change"

[[goals]]
name = "language"
reference = "./learn/math-physics/reference/calc_language.md"
status = "completed"
tasks = []

[[goals]]
name = "change"
reference = "./learn/math-physics/reference/calc_change.md"
status = "in_progress"
tasks = []

[[goals]]
name = "accumulation"
reference = "./learn/math-physics/reference/calc_accumulation.md"
status = "todo"
tasks = []

[[goals]]
name = "flow"
reference = "./learn/math-physics/reference/calc_flow.md"
status = "todo"
tasks = []

[[goals]]
name = "differential-equations"
reference = "./learn/math-physics/reference/calc_differential-equations.md"
status = "todo"
tasks = []
