name = "CHARGE Yhat Check-In"
slug = "charge_yhat_check_in"
description = """
Agenda:
[image.png]

________________________________________________________________________________
Microsoft Teams meeting
Join: https://teams.microsoft.com/meet/37307585320191?p=pWUHi8Xov4gYY9TbJe
Meeting ID: 373 075 853 201 91
Passcode: Bq3nG9e9
________________________________
Need help?<https://aka.ms/JoinTeamsMeeting?omkt=en-GB> | System reference<https://teams.microsoft.com/l/meetup-join/19%3ameeting_YmQ0MjY4ZDUtMDk3ZS00ZjJkLWFjMDAtMThmYjNmNzdlYmFh%40thread.v2/0?context=%7b%22Tid%22%3a%22a75f239e-0ade-4dfb-a4b0-6a88780803f1%22%2c%22Oid%22%3a%22b42a7463-535b-4f42-af66-3a061b138b47%22%7d>
For organisers: Meeting options<https://teams.microsoft.com/meetingOptions/?organizerId=b42a7463-535b-4f42-af66-3a061b138b47&tenantId=a75f239e-0ade-4dfb-a4b0-6a88780803f1&threadId=19_meeting_YmQ0MjY4ZDUtMDk3ZS00ZjJkLWFjMDAtMThmYjNmNzdlYmFh@thread.v2&messageId=0&language=en-GB>
________________________________________________________________________________

Location: Microsoft Teams Meeting"""
status = "completed"
created = "2026-03-31"
due = "2026-03-24T09:00:00+02:00"
completed_at = "2026-03-31"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "_60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g70pjccho711jce23890k8gpg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g8go4cgpg8d2kcg9h8p332h1k8p0jge9h6cr36h1l8orkah9p70q0"
last_modified = "2026-03-31T12:57:54.460199"
has_subtasks = false
parent = ""
