name = "CHARGE | Yhat - Vouchers project"
slug = "charge_yhat_vouchers_project"
description = """
Agenda:
[image.png]

________________________________________________________________________________
Microsoft Teams meeting
Join: https://teams.microsoft.com/meet/33725427897986?p=cV7CwzKLWajBrvA0Ds
Meeting ID: 337 254 278 979 86
Passcode: Kk7EJ9GA
________________________________
Need help?<https://aka.ms/JoinTeamsMeeting?omkt=en-GB> | System reference<https://teams.microsoft.com/l/meetup-join/19%3ameeting_OGRhZThhOTUtZWIyMi00YTViLWIzNzMtZmZmYjU1ODJmZDdh%40thread.v2/0?context=%7b%22Tid%22%3a%22a75f239e-0ade-4dfb-a4b0-6a88780803f1%22%2c%22Oid%22%3a%22b42a7463-535b-4f42-af66-3a061b138b47%22%7d>
For organisers: Meeting options<https://teams.microsoft.com/meetingOptions/?organizerId=b42a7463-535b-4f42-af66-3a061b138b47&tenantId=a75f239e-0ade-4dfb-a4b0-6a88780803f1&threadId=19_meeting_OGRhZThhOTUtZWIyMi00YTViLWIzNzMtZmZmYjU1ODJmZDdh@thread.v2&messageId=0&language=en-GB>
________________________________________________________________________________

Location: Microsoft Teams Meeting"""
status = "completed"
created = "2026-03-31"
due = "2026-03-20T13:00:00+02:00"
completed_at = "2026-03-31"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "_60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g6d0jgd9h68p46e9o88rk8gpg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g8gq3adi275232dho6cr44e1k6ks32h1g8l0j4ghi6ss4adph74sg"
last_modified = "2026-03-31T12:57:54.458569"
has_subtasks = false
parent = ""
