name = "FW: Philip Tendani catchup"
slug = "fw_philip_tendani_catchup"
description = """


Kind regards
Philip

[cid:image001.png@01DB6271.94B889F0]
From: Philip Nel <philip@charge.co.za>
Date: Monday, 23 March 2026 at 13:31
To: Tendani Mukhithi <tendani@charge.co.za>
Subject: Philip Tendani catchup

Agenda:

  *
N3 stations critical path
  *
Ad hoc tasks

________________________________________________________________________________
Microsoft Teams meeting
Join: https://teams.microsoft.com/meet/32835527049526?p=VdA3xSmupygq2qSV3F
Meeting ID: 328 355 270 495 26
Passcode: cn9YX7sD
________________________________
Need help?<https://aka.ms/JoinTeamsMeeting?omkt=en-GB> | System reference<https://teams.microsoft.com/l/meetup-join/19%3ameeting_NDI4MGFiYzEtZDBjMi00NjdmLWJhNmItMmEyOGQ4YzgwMjk3%40thread.v2/0?context=%7b%22Tid%22%3a%22a75f239e-0ade-4dfb-a4b0-6a88780803f1%22%2c%22Oid%22%3a%22b42a7463-535b-4f42-af66-3a061b138b47%22%7d>
For organisers: Meeting options<https://teams.microsoft.com/meetingOptions/?organizerId=b42a7463-535b-4f42-af66-3a061b138b47&tenantId=a75f239e-0ade-4dfb-a4b0-6a88780803f1&threadId=19_meeting_NDI4MGFiYzEtZDBjMi00NjdmLWJhNmItMmEyOGQ4YzgwMjk3@thread.v2&messageId=0&language=en-GB>
________________________________________________________________________________

Location: Microsoft Teams Meeting"""
status = "completed"
created = "2026-03-31"
due = "2026-03-23T13:30:00+02:00"
completed_at = "2026-03-31"
tags = [
    "gcal",
]
recurrence = ""
gcal_event_id = "_60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g6ko4acpg8ko46ghj890k8gpg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g6t2kch1m8p34ac9i6t33gdhk74sj2c246spj0cpo6osj6e9i8or0"
last_modified = "2026-03-31T12:57:54.459651"
has_subtasks = false
parent = ""
