name = "how-async-works"
current_goal = "Why Async is Different in Rust"

[[goals]]
name = "Why Async is Different in Rust"
reference = "./learn/rust/reference/async-book/ch01-why-async-is-different-in-rust.md"
status = "in_progress"
tasks = []

[[goals]]
name = "The Future Trait"
reference = "./learn/rust/reference/async-book/ch02-the-future-trait.md"
status = "todo"
tasks = []

[[goals]]
name = "How Poll Works"
reference = "./learn/rust/reference/async-book/ch03-how-poll-works.md"
status = "todo"
tasks = []

[[goals]]
name = "Pin and Unpin"
reference = "./learn/rust/reference/async-book/ch04-pin-and-unpin.md"
status = "todo"
tasks = []
