[[tasks]]
slug = "scaffold_nexus_learn_c_course"
name = "Scaffold Nexus Learn C course"
path = "./manage/tasks/scaffold_nexus_learn_c_course.toml"
parent = ""

[[tasks]]
slug = "lunch_with_mike"
name = "Lunch with Mike"
path = "./manage/tasks/lunch_with_mike.toml"
due = "2026-05-04T12:00:00"
parent = ""

[[tasks]]
slug = "scaffold_elixir_agent_jido_course"
name = "Scaffold Elixir Agent Jido course"
path = "./manage/tasks/scaffold_elixir_agent_jido_course.toml"
parent = ""

[[tasks]]
slug = "fix_nexus_learning_module_to_support_multiple_sessions_per_day"
name = "Fix nexus learning module to support multiple sessions per day"
path = "./manage/tasks/fix_nexus_learning_module_to_support_multiple_sessions_per_day.toml"
parent = ""
